CREATE DATABASE IF NOT EXISTS itmp DEFAULT CHARACTER SET UTF8 COLLATE UTF8_HUNGARIAN_CI;

USE itmp;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENET PRIMARY KEY,
    name VARCHAR(255),
    email VARCHAR(255)
);